modules/users/urls.py
from django.shortcuts import render
from django.urls import path, include

from modules.users.views import LoginView, ResetView, ForgotView, LogoutView, ProfileView, CreateView, ListUserView, \
    UserRemoveView, ActivateView, UserEditView, RangRemoveView, RangsCreateView, ListRangView, RangEditView, \
    UserProfileView, AvatarChangeView

urlpatterns = (
    path('login/', LoginView.as_view(), name="user_login_view"),
    path('logout/', LogoutView.as_view(), name='user_logout_view'),
    path('reset/<uidb64>/<token>/', ResetView.as_view(), name="user_reset_view"),
    path('forgot/', ForgotView.as_view(), name="user_forgot_view"),
    path('profile/', ProfileView.as_view(), name="profile_view"),
    path('create/', CreateView.as_view(), name="user_create_view"),
    path('list/', ListUserView.as_view(), name="user_list_view"),
    path('edit/<int:pk>/', UserEditView.as_view(), name="user_edit_view"),
    path('remove/<int:pk>/', UserRemoveView.as_view(), name="user_remove_view"),
    path('activate/<uidb64>/<token>/', ActivateView.as_view(), name="user_activate_view"),
    path('rang/create/', RangsCreateView.as_view(), name="rang_create_view"),
    path('rang/remove<int:pk>', RangRemoveView.as_view(), name="rang_remove_view"),
    path('rang/list', ListRangView.as_view(), name="rang_list_view"),
    path('rang/edit/<int:pk>/', RangEditView.as_view(), name="rang_edit_view"),
    path('profil/<str:username>/', UserProfileView.as_view(), name="user_profile_view"),
    path('change/', AvatarChangeView.as_view(), name="user_avatar_change_view"),
)

zobin/urls.py
"""zobin URL Configuration

The `urlpatterns` list routes URLs to modules. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function modules
    1. Add an import:  from my_app import modules
    2. Add a URL to urlpatterns:  path('', modules.home, name='home')
Class-based modules
    1. Add an import:  from other_app.modules import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include


def page_not_found_view(request, exception):
    return render(request, 'sites/base/notFound.html', status=404)


def page_not_permission_view(request, exception):
    return render(request, 'sites/base/noPermissions.html', status=403)


urlpatterns = [
    path('user/', include('modules.users.urls')),
    path('wniosek/', include('modules.wnioski.urls')),
    path('', include('modules.main.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = page_not_found_view
handler403 = page_not_permission_view


print("WEBSITE URLS loaded...\n\n")

modules/users/models.py
import datetime

from django.conf.global_settings import MEDIA_URL
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import AbstractUser, UserManager, PermissionsMixin, User
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext as _


# Create your models here.


class Server(models.Model):
    serwer = models.CharField(max_length=50)

    class Meta:
        verbose_name = _('Serwer')
        verbose_name_plural = _('Serwery')

    def __str__(self):
        return self.serwer


class Rangs(models.Model):
    ranga = models.CharField(max_length=50)

    class Meta:
        verbose_name = _('Ranga')
        verbose_name_plural = _('Rangi')

    def __str__(self):
        return self.ranga


class PanelUser(AbstractBaseUser, PermissionsMixin):
    username_validator = UnicodeUsernameValidator()
    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    password = models.CharField(_('password'), max_length=128)
    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=False,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    is_admin = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    email = models.EmailField(_('email address'), unique=True)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    GENDER_MALE = 1
    GENDER_FEMALE = 2
    GENDER_CHOICES = [
        (GENDER_MALE, _("Male")),
        (GENDER_FEMALE, _("Female")),
    ]

    DZIAL_CZLONEK = 1
    DZIAL_DYREKCJA = 2
    DZIAL_ZARZAD = 3
    DZIAL_CHOICES = [
        (DZIAL_CZLONEK, _("Członek")),
        (DZIAL_DYREKCJA, _("Dyrekcja")),
        (DZIAL_ZARZAD, _("Zarząd")),
    ]

    avatar = models.ImageField(blank=True, null=True, upload_to='avatars', default='avatars/1.png')
    baner = models.ImageField(blank=True, null=True, upload_to='baner')

    birthday = models.DateField(blank=True, null=True)
    gender = models.PositiveSmallIntegerField(choices=GENDER_CHOICES, blank=True, default=GENDER_MALE)

    ranga = models.ForeignKey(Rangs, related_name="rang", on_delete=models.CASCADE, blank=True, null=True)
    dzial = models.PositiveSmallIntegerField(choices=DZIAL_CHOICES, blank=True, default=DZIAL_CZLONEK)
    serwer = models.ForeignKey(Server, related_name="server", blank=True, on_delete=models.CASCADE, null=True)

    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = _('Użytkownik')
        verbose_name_plural = _('Użytkownicy')

    def __str__(self):
        return "Profile: %s" % self.username

    def age(self):
        return int((datetime.date.today() - self.birthday).days / 365.25)

modules/users/views/activate_view.py
import json

from django.contrib import messages
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.utils.translation import gettext as _

from modules.users.forms import ForgotForm, ResetPasswordForm
from modules.users.models import PanelUser
from zobin.settings import DEFAULT_FROM_EMAIL


class ActivateView(View):
    activation_token = PasswordResetTokenGenerator()
    title = 'Aktywuj konto'

    def get(self, request, uidb64, token):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse_lazy('main_dashboard_view'))

        uid = force_text(urlsafe_base64_decode(uidb64))
        user = PanelUser.objects.get(pk=uid)

        if self.activation_token.check_token(user,token):
            context = {
                'title': self.title,
                'uid': uidb64,
                'token': self.activation_token.make_token(user),
                'form_pass': ResetPasswordForm(user)
            }
            return render(request, 'sites/users/activate.html', context)
        else:
            messages.error(request, json.dumps(
                {
                    'body': _("Link do aktywacji konta wygasł. Skontaktuj sie ze wsparciem klienta, aby zmienić hasło."),
                    'title': _("Nie udało sie aktywować konta!")
                }
            ))
        return HttpResponseRedirect(reverse_lazy("main_dashboard_view"))

    def post(self,request,uidb64,token):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse_lazy('main_dashboard_view'))

        uid = force_text(urlsafe_base64_decode(uidb64))
        user = PanelUser.objects.get(pk=uid)
        reset_form = ResetPasswordForm(data=request.POST, user=user)

        context = {
            'title': self.title,
            'reset_form': reset_form,
            'uid': uidb64,
            'token': token
        }

        if self.activation_token.check_token(user, token):
            if reset_form.is_valid():
                reset_form.save()
                user.is_active = True
                user.save()
                messages.info(request, json.dumps(
                    {
                        'body': _("Twoje konto zostało aktywowane oraz hasło ustawiono pomyślnie"),
                        'title': _("Konto aktywowane!")
                    }
                ))
                return HttpResponseRedirect(reverse_lazy("user_login_view"))
            else:
                for header, msg_list in reset_form.errors.as_data().items():
                    for error_msg in msg_list:
                        messages.error(request, json.dumps(
                            {
                                'body': str(error_msg.message).capitalize(),
                                'title': _("The current form is not valid")
                            }
                        ))
                return render(request, "sites/users/activate.html", context)
        else:
            messages.error(request, json.dumps(
                {
                    'body': _("Link do aktywacji konta wygasł. Skontaktuj sie ze wsparciem klienta, aby zmienić hasło."),
                    'title': _("Nie udało sie aktywować konta!")
                }
            ))
            return HttpResponseRedirect(reverse_lazy("main_dashboard_view"))

modules/users/views/create_view.py
import json

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Permission
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.views import View

from modules.users.forms import CreateUserForm, RangForm

from django.utils.translation import gettext as _

from modules.users.models import PanelUser
from zobin.settings import DEFAULT_FROM_EMAIL


class CreateView(PermissionRequiredMixin, LoginRequiredMixin, View):
    permission_required = 'zarzad'
    login_url = reverse_lazy('user_login_view')
    title = "Create User"
    activation_token = PasswordResetTokenGenerator()

    def get(self, request):
        context = {
            'title': self.title.title,
            'user_form': CreateUserForm(),
        }
        return render(request, 'sites/users/create.html', context)

    def post(self, request):
        site = get_current_site(request)

        user_form = CreateUserForm(request.POST)

        context = {
            'title': self.title,
            "user_form": user_form,
        }

        if user_form.is_valid():
            content_type = ContentType.objects.get_for_model(PanelUser)
            permission = Permission.objects.get(
                codename='zarzad',
                content_type=content_type,
            )
            user = user_form.save()
            if user.dzial == 3:
                user.user_permissions.add(permission)
                user.save()
            user.save()

            mail_content = {
                'user': user,
                'domain': site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': self.activation_token.make_token(user)
            }

            message = render_to_string('sites/mail/account_confirm.html', mail_content)

            send_mail(
                subject=_("Wiadomość potwierdzająca"),
                message=_('Welcome %s,\n\n You get this mail because you do yours first right step, '
                          'you registered a account on %s and we are very happy about it!\n\nYour login '
                          'credentials:\nUsername: %s\n \nMake sure to keep this e-mail secure!\n\nTo '
                          'complete the registration process please verify you account by clicking on this '
                          'link:\nhttp://%s/%s/%s') % (
                            user.first_name, site.domain, user.username, site.domain,
                            mail_content.get('uid', ''),
                            mail_content.get('token', '')
                        ),
                from_email=DEFAULT_FROM_EMAIL,
                recipient_list=[user.email],
                fail_silently=True,
                html_message=message
            )

            messages.info(request, json.dumps(
                {
                    'body': _("Link aktywacyjny został wysłany do %s" % user.username),
                    'title': _("Konto założone!")
                }
            ))
            return HttpResponseRedirect(reverse_lazy("main_dashboard_view"))
        else:
            for header, msg_list in user_form.errors.as_data().items():
                for error_msg in msg_list:
                    messages.error(request, json.dumps(
                        {
                            'body': str(error_msg.message).capitalize(),
                            'title': _("Błąd!")
                        }
                    ))

        return render(request, "sites/users/create.html", context)


class RangsCreateView(PermissionRequiredMixin, LoginRequiredMixin, View):
    permission_required = 'zarzad'
    login_url = reverse_lazy('user_login_view')
    title = "Stwórz range"
    activation_token = PasswordResetTokenGenerator()

    def get(self, request):
        context = {
            'title': self.title.title,
            'rang_form': RangForm(),
        }
        return render(request, 'sites/rangs/create.html', context)

    def post(self, request):

        rang_form = RangForm(request.POST)

        context = {
            'title': self.title,
            "rang_form": rang_form,
        }

        if rang_form.is_valid():
            ranga = rang_form.save()
            ranga.save()

            messages.info(request, json.dumps(
                {
                    'body': _("Pomyślnie stworzono rangę %s." % ranga.ranga),
                    'title': _("Dodano range!")
                }
            ))
            return HttpResponseRedirect(reverse_lazy("main_dashboard_view"))
        else:
            for header, msg_list in rang_form.errors.as_data().items():
                for error_msg in msg_list:
                    messages.error(request, json.dumps(
                        {
                            'body': str(error_msg.message).capitalize(),
                            'title': _("Błąd!")
                        }
                    ))

        return render(request, "sites/rangs/create.html", context)

modules/users/views/list_user_view.py
import json
import datetime

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView

from modules.users.forms import CreateUserForm

from django.utils.translation import gettext as _

from modules.users.models import PanelUser, Rangs
from rest_framework import viewsets, generics


class ListUserView(PermissionRequiredMixin, LoginRequiredMixin, APIView):
    permission_required = 'zarzad'
    login_url = reverse_lazy('user_login_view')
    title = 'Lista użytkowników'
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'sites/users/list_users.html'

    def get(self, request):
        queryset = PanelUser.objects.all()
        context = {
            'users': queryset,
            'title': self.title,
        }
        return Response(context)


class ListRangView(PermissionRequiredMixin, LoginRequiredMixin, APIView):
    permission_required = 'zarzad'
    login_url = reverse_lazy('user_login_view')
    title = 'Lista użytkowników'
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'sites/rangs/list.html'

    def get(self, request):
        context = {
            'rangs': Rangs.objects.all(),
            'title': self.title,
        }
        return Response(context)

templates/sites/users/list_users.html
{% extends 'sites/base/base.html' %}
{% load static %}
{% block content %}

<div class="content-body">
            <div class="container-fluid">
                <div class="row page-titles mx-0">
                    <div class="col-sm-6 p-md-0">
                        <div class="welcome-text">
                            <h4>Cześć, {{ request.user.username|capfirst }}</h4>
                            <span class="ml-1">W tej sekcji znajdują się wszyscy użytkownicy. Jeśli tu wszedłeś znaczy że należysz do działu zarządu!</span>
                        </div>
                    </div>
                    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0)">Użytkownicy</a></li>
                            <li class="breadcrumb-item active"><a href="javascript:void(0)">Zarządzanie</a></li>
                        </ol>
                    </div>
                </div>
                <!-- row -->
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Lista członków projektu</h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table id="example" class="display" style="min-width: 845px">
                                        <thead>
                                            <tr>
                                                <th>Nick</th>
                                                <th>Imię</th>
                                                <th>Email</th>
                                                <th>Status</th>
                                                <th>Wiek</th>
                                                <th>Dział</th>
                                                <th>Ranga</th>
                                                <th>Serwer</th>
                                                <th>Edycja</th>
                                                <th>Kasacja</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for user in users %}
                                                <tr>
                                                    <td><a href="{% url 'user_profile_view' username=user.username %}">{{ user.username }}</a></td>
                                                    <td>{{ user.first_name }}</td>
                                                    <td>{{ user.email }}</td>
                                                    <td>{% if user.is_active %}
                                                            <span style="color:green;">Aktywny</span>
                                                        {% else %}
                                                            <span style="color:red;">Nieaktywny</span>
                                                        {% endif %}
                                                    </td>
                                                    <td>{{ user.age }}</td>
                                                    <td>{{ user.get_dzial_display }}</td>
                                                    <td>{{ user.ranga }}</td>
                                                    <td>{{ user.serwer }}</td>
                                                    <td><a href="{% url 'user_edit_view' user.pk %}" class="btn btn-info">Edytuj</a></td>
                                                    <td><a href="{% url 'user_remove_view' user.pk %}" class="btn btn-danger">Usuń</a></td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock content %}

templates/sites/users/profile_user.html
{% extends 'sites/base/base.html' %}
{% load static %}

{% block content %}
<div class="content-body">
    <div class="container-fluid">
        <!-- row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="profile">
                    <div class="profile-head">
                        <div class="photo-content">
                            <div class="cover-photo" style="background: url({{ profile.baner.url }}); background-size: cover; background-position: center;"></div>
                            <div class="profile-photo">
                                <img src="{{ profile.avatar.url }}" class="img-fluid rounded-circle" height="150" width="150" alt="">
                            </div>
                        </div>
                        <div class="profile-info">
                            <div class="row justify-content-center">
                                <div class="col-xl-8">
                                    <div class="row">
                                        <div class="col-xl-4 col-sm-4 border-right-1 prf-col">
                                            <div class="profile-name">
                                                <h4 class="text-primary">{{ profile.username }}</h4>
                                                <p>{{ profile.ranga }}</p>
                                            </div>
                                        </div>
                                        <div class="col-xl-4 col-sm-4 border-right-1 prf-col">
                                            <div class="profile-email">
                                                <h4 class="text-muted">{{ profile.email }}</h4>
                                                <p>Email</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <div class="profile-statistics">
                            <div class="text-center mt-4 border-bottom-1 pb-3">
                                <div class="row">
                                    <div class="col">
                                        <h3 class="m-b-0">150</h3><span>Skargi</span>
                                    </div>
                                    <div class="col">
                                        <h3 class="m-b-0">140</h3><span>Pochwały</span>
                                    </div>

                                </div>
                                <div class="mt-4"><a href="" class="btn btn-primary pl-5 pr-5 mr-3 mb-4">Pochwal</a>
                                 <a href="" class="btn btn-primary pl-5 pr-5 mr-3 mb-4">Oskarż</a>
                                    <a href="" class="btn btn-dark pl-5 pr-5 mb-4">Wyślij wiadomość</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="card">
                    <div class="card-body">
                        <div class="profile-tab">
                            <div class="custom-tab-1">
                                <ul class="nav nav-tabs">
                                    <li class="nav-item"><a href="#wnioski" data-toggle="tab" class="nav-link active show">Wnioski</a>
                                    </li>
                                    <li class="nav-item"><a href="#kary" data-toggle="tab" class="nav-link">Nałożone kary</a>
                                    </li>
                                    <li class="nav-item"><a href="#about-me" data-toggle="tab" class="nav-link">O mnie</a>
                                    </li>
                                </ul>
                                <div class="tab-content">
                                    <div id="wnioski" class="tab-pane fade active show">
                                        <!-- TODO dodac wnioski -->
                                    </div>
                                    <div id="kary" class="tab-pane fade">
                                        <!-- TODO dodac kary -->
                                    </div>
                                    <div id="about-me" class="tab-pane fade">
                                        <div class="profile-about-me">
                                            <div class="pt-4 border-bottom-1 pb-4">
                                                <h4 class="text-primary">O mnie</h4>
                                                <p>A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence was created for the
                                                    bliss of souls like mine.I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents.</p>
                                            </div>
                                        </div>
                                        <div class="profile-personal-info">
                                            <h4 class="text-primary mb-4">Personal Information</h4>
                                            <div class="row mb-4">
                                                <div class="col-3">
                                                    <h5 class="f-w-500">Name <span class="pull-right">:</span>
                                                    </h5>
                                                </div>
                                                <div class="col-9"><span>{{ profile.first_name }}</span>
                                                </div>
                                            </div>
                                            <div class="row mb-4">
                                                <div class="col-3">
                                                    <h5 class="f-w-500">Email <span class="pull-right">:</span>
                                                    </h5>
                                                </div>
                                                <div class="col-9"><span>{{ profile.email }}</span>
                                                </div>
                                            </div>
                                            <div class="row mb-4">
                                                <div class="col-3">
                                                    <h5 class="f-w-500">Wiek <span class="pull-right">:</span>
                                                    </h5>
                                                </div>
                                                <div class="col-9"><span>{{ profile.age }}</span>
                                                </div>
                                            </div>
                                            <div class="row mb-4">
                                                <div class="col-3">
                                                    <h5 class="f-w-500">Dział <span class="pull-right">:</span>
                                                    </h5>
                                                </div>
                                                <div class="col-9"><span>{{ profile.get_dzial_display }}</span>
                                                </div>
                                            </div>
                                            <div class="row mb-4">
                                                <div class="col-3">
                                                    <h5 class="f-w-500">Ranga <span class="pull-right">:</span>
                                                    </h5>
                                                </div>
                                                <div class="col-9"><span>{{ profile.ranga }}</span>
                                                </div>
                                            </div>
                                            <div class="row mb-4">
                                                <div class="col-3">
                                                    <h5 class="f-w-500">Serwer <span class="pull-right">:</span>
                                                    </h5>
                                                </div>
                                                <div class="col-9"><span>{{ profile.serwer }}</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}